version: "3.7"
services:
  db-golang-coding-prep:
    container_name: "golang-coding-prep"
    image: "postgres:12"
    volumes:
#      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - golang-coding-prep-pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=partitioning
    ports:
      - "15432:5432"
volumes:
  golang-coding-prep-pg: